language: common-lisp
# Attempt to run as more efficient container
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
# Speculatively hook into Coveralls <https://coveralls.io/>
    - COVERAGE_EXCLUDE=t/
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
# Uncomment to enable the build farm resource to be spent on implementations that might actually produce usefull results    
#    - LISP=abcl-bin
#    - LISP=ecl
#    - LISP=clisp
#    - LISP=clasp

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
# Add needed Quicklisp dependencies for testing here  
  - ros install prove
  - ros install lisp-unit

script:
  - ros -e '(ql:quickload :emotiq-tests)
            (or (lisp-unit:run-tests :all :emotiq-tests)
                (uiop:quit -1))'
  - ros -s prove
        -e '(or (prove:run :emotiq-prove)
                (uiop:quit -1))'
  - ros -s lisp-unit
        -e '(ql:quickload :emotiq-tests)
            (or (lisp-unit:run-tests :all :cosi-test)
                (uiop:quit -1))'                         
  - ros -s prove
        -e '(or (prove:run :cosi-prove)
                (uiop:quit -1))'
  - ros -s prove -s cl-coveralls
        -e '(or (coveralls:with-coveralls (:exclude (list "t"))
                  (prove:run :emotiq-prove))
                (uiop:quit -1))'
